name: GitHub Actions Demo
on:
  push:
    branches: [main]
  pull_request:
jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.x
          cache: npm
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
