name: Unit Tests
on:
  push:
    branches: [main]
  pull_request:
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.x
          cache: npm
      - name: Install
        run: npm ci
      - name: Test
        run: npm run test:ci
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'test-results.xml'
      - name: Report Coverage
        uses: codecov/codecov-action@v3
        with:
          verbose: true
